name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.9]

    steps:
      - uses: actions/checkout@v3

#      # DJANGO CI
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Run Tests
#        run: |
#          python manage.py test


#      # upload docker image to HUB
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_TOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: kirilltrytobe/kirill-try-to-be-app:latest

      # DEPLOY on server
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /root/project_gitgub/kirill-try-to-be/
            git pull origin main
            git status
            docker stop $(docker ps -a -q)
            docker compose up -d
            
            
#            cd /var/www/youtube.com/
#            git pull origin main
#            git status
#            npm install --only=prod